### ISSUE TITLE
Cannot add anymore a sub-organization in the add-contact form

### ISSUE THREAD

**Issue by sgeulette** [collective/collective.contact.core#18]
Previously, with the add-contact form, it was possible to add a sub-organization after added an organization. This link isn't more proposed.

**Comment by sgeulette** [comment]
Maybe linked to the fact that the function directly appears on form load, without entry any organization and person.

**Comment by vincentfretin** [comment]
This is fixed. https://github.com/collective/collective.contact.core/commit/7e0685b60294618b0e252b1df23b4a71129e29f4 and test in https://github.com/collective/collective.contact.core/commit/f17a4bb984de0d3df0000206a18f86ebc98cff79
