### ISSUE TITLE
Installing this add-on break ZMI Zope root control panel (Debug Information)

### ISSUE THREAD

**Issue by keul** [collective/collective.contact.core#19]
Not sure is a problem of this add-on, maybe something related to dependencies

After adding this add-on to the buildout I'm no more able to access http://localhost:8080/Control_Panel/DebugInfo/manage_workspace:

    Traceback (innermost last):
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module ZPublisher.Publish, line 48, in call_object
      Module Shared.DC.Scripts.Bindings, line 322, in __call__
      Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
      Module App.special_dtml, line 185, in _exec
      Module DocumentTemplate.DT_In, line 630, in renderwob
      Module DocumentTemplate.DT_Util, line 210, in eval
       - __traceback_info__: refcount
      Module <string>, line 1, in <module>
      Module App.ApplicationManager, line 167, in refcount
      Module pip._vendor.six, line 90, in __get__
    AttributeError: winreg could not be imported

Looking more into this, `_winreg` is a Python module that must only be here on Windows.
If I search for who is importing it I get:

    $ grep -r winreg *|grep import
    Products.MimetypesRegistry-2.0.5-py2.7.egg/Products/MimetypesRegistry/mime_types/windows_mimetypes.py:import _winreg
    python_dateutil-1.5-py2.7.egg/dateutil/tzwin.py:import _winreg
    vobject-0.6.6-py2.7.egg/vobject/win32tz.py:import _winreg

Maybe one of the dependency is loading the windows module in any case?

**Comment by petschki** [comment]
hi, just got the same error on a Plone Site with `six = 1.5.x` installed ... I've upgraded to  `six = 1.9.0` and the error is gone ... hope this helps you too ...

**Comment by vincentfretin** [comment]
I close this if you say you only need to upgrade six to fix the issue.
