### ISSUE TITLE
person should be required in AddContact

### ISSUE THREAD

**Issue by ebrehault** [collective/collective.contact.core#20]
The AddContact form schema declared its `person` filed as required, but the `updateWidgets` method forces it to non-required.
It allows users to create contacts without person, which is wrong.
@vincentfretin I assume you made this hack for a good reason as explained here https://github.com/collective/collective.contact.core/blame/master/src/collective/contact/core/browser/addcontact.py#L310 , but do you have an idea about a possible solution?

**Comment by vincentfretin** [comment]
The following is possible with this AddContact form :

- Returning a contact (held position) when you select an organization and a person. Your use case apparently.
- Returning a person when you select only a person
- Returning a organization when you select only an organization. It's for this case I did the hack you mentioned. I want no required errors in the form if the IHeldPosition required fields are not filled.

In the case where you have configured a field like this

    contact_entreprise = ContactChoice(
        title=_(u"Contact dans l'entreprise"),
        source=ContactSourceBinder(portal_type=("held_position",)),
        )

you want indeed the person field to be really required.

I'm working on a fix with @cedricmessiant
