### ISSUE TITLE
Allow nested Directories or Subfolders

### ISSUE THREAD

**Issue by frisi** [collective/collective.contact.core#21]
We've got the usecase to support two groups of users:
- contact-editors
- contact-admins

contact-editors can:
- read / export / use all contacts within the directory
- only edit contacts they are responsible for

contact-admins can: 
- read / export / use all contacts within the directory
- edit all contacts within the directory

i'd implement this by allowing subfolders in directories (no nested directories since these define additional attributes (available organizationtypes and so on)

this way it is easy to grant the editor role to specific users for certain subfolders.
straight forward, and very plonish.

is this something you want collectice.contact.core to support?
i.e add a new type "subdirectory" or "directoryfolder" that is addable in directories and allows to add persons and organizations

thanks for your opinions @ebrehault @tdesvenain @vincentfretin @sgeulette (and of course other users of this package)

**Comment by ebrehault** [comment]
I am not sure about the possible side-effects if we manage person or org in subdirectories, but what's pretty sure is it will not break existing instances where all the objects in a unique folder (I mean your change should not "pollute" existing stuff).
So +1

I would recommend we have a specific permission for adding new subdirectory.

**Comment by frisi** [comment]
thanks for your feedback @ebrehault. 

what's your rationale for the separate permission for adding subdirectories? are you afraid contact-editors will start to create useless subdirectories?

how should adding contacts to a subdirectory work?
afaics facetednav hides the portal-columns (and therefor the navigation portlet).
so contact-editors need to navigate to "their" subfolder(s) using folder_contents view and click "add / person" there.
any ideas how this can be improved?

**Comment by ebrehault** [comment]
By adding a specific permission, we can make sure your new feature (adding sudirectories) can be hidden for users having the "App portal content" permission (so they might add new person or orga, but that's it).

Regarding adding contact: that's the kind of side-effects I was talking about :).
There are other issues, like for instance with the contact widget (from collective.contact.widget) which allows to create a new contact while creating/modifying another content, what if the current user is allowed to create contacts in such and such subfolder but not in the main directory? we need to change the UX (which is already quite complex) to address that.
I am sure there are dozen of other similar issues.

So as far as your subdirectories are managed in an automatic way (using content rules, or whatever), it will work, and it is harmless. But if you want it to work fine in all the collective contact specific UX elements, it will be a hard work.

**Comment by vincentfretin** [comment]
@frisi I think the code can become very complex in collective.contact.widget if you want to support subdirectories.
For your use cases, did you consider using borg local roles to assign dynamically roles from the value of a field? I don't know if you're familiar with this. For example I added in a project a behavior to held_position to add a roles field, the values are simple member or moderator of the organization. Moderators can edit the persons linked to this organization. Here an example of a borg local role:

```class OrganizationLocalRolesAdapter(grok.Adapter):                              
                                                                                
    """Give Reviewer role to the organization moderators and Editor role           
    to other contacts.                                                          
    """                                                                         
                                                                                
    grok.name("organization_local_roles")                                       
    grok.context(IOrganization)                                                 
                                                                                
    def getRoles(self, principal_id):                                           
        """Return roles for this principal in this context."""                  
        members = get_contacts(self.context, only_users=True)                   
        moderators = get_moderators(self.context)                               
        person = get_person_from_user_id(principal_id)                          
        if person in moderators:                                                
            return ['Reviewer', 'Editor']                                       
        elif person in members:                                                 
            return ['Editor']                                                   
        else:                                                                   
            return []                                                           
                                                                                
    def getAllRoles(self):                                                      
        """Return all the local roles assigned in this context.                 
                                                                                
        Return value looks like [(principal_id, [role1, role2]), ...]           
        """                                                                     
        allroles = []                                                           
        moderators = get_moderators(self.context)                               
        for person in get_contacts(self.context, only_users=True):              
            person_id = get_userid_from_person(person)                          
            if person in moderators:                                            
                allroles.append((person_id, ['Editor', 'Reviewer']))            
            else:                                                               
                allroles.append((person_id, ['Editor']))                        
                                                                                
        return allroles
```

**Comment by vincentfretin** [comment]
I think we answered it. Your on your own for your specific use cases. :)

**Comment by frisi** [comment]
yes it does - thanks for your thoughts and answers @vincentfretin  and @ebrehault
