### ISSUE TITLE
Plone 5(.1) compatibility

### ISSUE THREAD

**Issue by agitator** [collective/collective.contact.core#23]
Tried to udpate the package locally but got stuck with changes in plone.app.linkintegrity
What are the plans? Problems? Blockers?

@vincentfretin @ebrehault @sgeulette @frisi @fredvd

**Comment by ebrehault** [comment]
@agitator, on my side, I use collective.contact with eea.facetednav, and it is a very important part of the UI for my customers.
Considering eea.faceted is not migrated on Plone 5, I haven't planned anything about collective.contact on Plone 5 for now.
So let's say eea.faceted is my blocker here, even if it is not directly connected to collective.contact.

**Comment by sgeulette** [comment]
@agitator, we also use all contact products in several web applications (more than 50 instances) and p.a.linkintegrity is very important for us. We have to keep plone 4 compatibility for now.

**Comment by agitator** [comment]
Client decided to go with collective.contact.core for his Plone 5 project. 

I added a plone5 branch and started by disabling features to have it running on Plone 5.
Will update those features as needed for the project.

**Comment by agitator** [comment]
There are two bugs with Plone5 that we found, thanx @tdesvenain 

- Organization is not selected by default on the "Create Contact" form from an organization
- If you create a new position within that form, it shouldn't be redirected, but update the already open popups

**Comment by tdesvenain** [comment]
> There are two bugs with Plone5 that we found, thanx @tdesvenain
> 
> * Organization is not selected by default on the "Create Contact" form from an organization
> * If you create a new position within that form, it shouldn't be redirected, but update the already open popups

I fixed those two bugs in recent commits in plone5 branch

**Comment by tdesvenain** [comment]
> Tried to udpate the package locally but got stuck with changes in plone.app.linkintegrity
> What are the plans? Problems? Blockers?
> 
> @vincentfretin @ebrehault @sgeulette @frisi @fredvd

Hi @agitator i don't remember what problem we get with plone.linkintegrity. which features has been disbled in plone5 branch ?

**Comment by agitator** [comment]
As far as I remember it didn't even start 🤷🏻‍♂️

**Comment by agitator** [comment]
https://github.com/collective/collective.contact.core/issues/23 was imho the only thing.

Also I'd say als grok remains should be extinct for Plone 5 release ;-)

**Comment by tdesvenain** [comment]
i have fixed all those problems in plone5 branch now
