### ISSUE TITLE
workflow: permission to view contacts

### ISSUE THREAD

**Issue by frisi** [collective/collective.contact.core#26]
the role member can view contacts in the active state
https://github.com/collective/collective.contact.core/blob/1.9/src/collective/contact/core/profiles/default/workflows/collective_contact_core_workflow/definition.xml#L30

wouldn't it be more plone-standard-like to grant the view permission to
`Manager, Owner, Reader`
and remove `Contributor and Member` here?

especially since all users with a login in plone are Members by default

**Comment by frisi** [comment]
@vincentfretin - what is your opinion on this?

**Comment by vincentfretin** [comment]
I don't understand why you want to remove the Member role from the View permission in the active state. We want all members to view the profile of all other active members, this is on purpose. This is our use case on several projects anyway.
For the Contributor role, it has the Modify portal content permission, so it needs the View permission too.

If you want another workflow, you can define another one in your own module and assign it to the person content type.

**Comment by frisi** [comment]
thanks for your feedback @vincentfretin 

i'll try to explain this in more detail:

plone grants the member role to all users added to the plonesite by default.
this makes it hard for integrators to create a contact-directory that is only accessible to to a certain subset of users.


in a default plone installation, the Member role does not have view permission.
neither on the permisson settings on the plone portal

![plone-default-view-permission](https://cloud.githubusercontent.com/assets/1120517/21935647/991545dc-d9ae-11e6-8cbb-7f97b1e8ccee.png)

nor in the default workflow
![plone-default-view-workflow](https://cloud.githubusercontent.com/assets/1120517/21935665/a9d17558-d9ae-11e6-8d5b-c7319a9edb53.png)


you are right about keeping the view permission for the contributor:
just saw that in the private state of simple_publication_workflow the view permission is granted to editor and contributor too. (i first looked at published, where it is granted to anonymous and therefore not needed for any other roles)

**Comment by vincentfretin** [comment]
Yes, ok, I understand that in your case you want to restrict the View to a subset of your members. This is a specific case and you can easily do that by changing the workflow in your project. I don't see another way to do that without changing the current behavior we have today where we want all authenticated users to see the active persons. Or am I missing something?

**Comment by vincentfretin** [comment]
There is no particular action to do here, this is a specific use case you can add to your project.

**Comment by frisi** [comment]
i'm ok with chaning the workflow for our project.
i understand that you'd have to change the workflow of your project if you'd implement the changes proposed in this ticket.
however, i don't think that granting the view permission to the member role was a good design decision since it does not fit plone's permission model.

**Comment by vincentfretin** [comment]
Of course it fits the plone's permission model, it depends of the use case! Your assumptions was based apparently on the simple_publication_workflow. There is several workflows you can choose from in a default Plone installation. What about the intranet workflow ? The internal state do use the Member role, like here.

**Comment by frisi** [comment]
point taken @vincentfretin  - i did not look at the intranet_worflow ;-)
