### ISSUE TITLE
address format localizations

### ISSUE THREAD

**Issue by agitator** [collective/collective.contact.core#29]
the standard address format (french) is
10 Streetname

in german the address would be 
Streetname 10

how could this be implemented (besides overriding views)?

**Comment by agitator** [comment]
it would also be nice to be able to change the order within edit

**Comment by cedricmessiant** [comment]
Maybe we should implement something like `get_street_address` in Address view and check the localization there to determine the order for number and street. 
I don't really know if address format differ more largely (city, zip code, etc) according to languages or if it is limited to street/number order.

**Comment by vincentfretin** [comment]
Not tested, but I think you can just change in browser/templates/address.pt:
```
    <div class="street-address" class="address_line street-address" i18n:translate="address_line">
        <span i18n:name="number" tal:replace="address/number"></span>
        <span i18n:name="street" tal:replace="address/street"></span>
</div>
```
and translate in German address_line msgid to "${street} ${number}"
If you can do a PR, I'll merge it.
