### ISSUE TITLE
localization for Person Title

### ISSUE THREAD

**Issue by agitator** [collective/collective.contact.core#30]
Person title is added automically based on gender and can be overridden.
How to add localized terms for other languages?

**Comment by cedricmessiant** [comment]
Unfortunately this is done in javascript ( https://github.com/collective/collective.contact.core/blob/master/src/collective/contact/core/browser/static/forms.js#L4 ). I'm not sure on how to do this cleanly

**Comment by cedricmessiant** [comment]
Fixed by 5c5e5b997b427349184ff1c226cdf0939c94a50e
You can now translate the terms.
