### ISSUE TITLE
streetnumber shown before street

### ISSUE THREAD

**Issue by frisi** [collective/collective.contact.core#35]
is there a reason why the number of the screet is shown before the street name?

maybe this is handeled differently in different countries?
at least in germany/austria/uk people are used to this format:
`<streetname> <number>`

collective contact core shows the input field for the number above the input field for the street and also in the view template:
eg
```
Address:
1 Kirchplatz 
```

is this a localization problem, or can we change the order to streetname - streetnumber and it fits your usecase in france too?

**Comment by vincentfretin** [comment]
The streetnumber is shown first in France.
I already replied to this in #29 with a solution, just waiting for a PR. ;)
I close this issue as duplicate.

**Comment by frisi** [comment]
thanks for your reply vincent and sorry for not searching the tracker before posting my issue
