### ISSUE TITLE
Display help positions the same way everywhere

### ISSUE THREAD

**Issue by gbastien** [collective/collective.contact.core#47]
Hi @vincentfretin @tdesvenain 

On an organization, held positions linked to a position are not displayed the same way "other contacts" that also displays held positions.

First case are displayed as links and "other contacts" will display the contact logo and so on.

There should be a "@@display-help_position" view called on every held_position displayed everywhere so it is consistent.

Does that seem correct to you?  If so, I would propose a PR.

Gauthier

**Comment by vincentfretin** [comment]
Hi,
In my project, I have cutomized almost all views, so I don't really care, go ahead and modify it as you wish :)

**Comment by gbastien** [comment]
Hi @vincentfretin @tdesvenain 

we still a bit stuck on this problem and we would like to make things work a coherent way from content to content.
Title of a content is displayed differently from place to place, including full path to content or not and so on.  We discussed it with @sgeulette and finally, that would be nice to :

- display content title the same way everywhere, in the configuration as well as in the select boxes or in various views;
- display the "real" title of content and additional informations between (), so not sometimes with ":" or so, so for example for a position we would have "Real position title (additional informations)".  When we have a title we display it clearly as first part of the title;
- if we do not have title, like for held_position, we would display "person (org, position)", in case the hp has a label, it would be "person, label (org, position)".

It is finally more or less the way it is displayed for now but what we would like is things to be systematically displayed the same way everywhere.

A second thing we would like to do is to identify easily in the configuration the type of content we are on.  It is often difficult to know that we are on a position, a held_position or a person.  We would like to display the content type icon before the title, what do you think?

Gauthier

**Comment by vincentfretin** [comment]
Hi, sure, you can add the content type icon next to the title, I'm ok with this.

**Comment by gbastien** [comment]
Fixed by #48
