### ISSUE TITLE
Adding a directory show required fields (position/organisation types) that do not work

### ISSUE THREAD

**Issue by fredvd** [collective/collective.contact.core#6]
When I add a new directory to a plone site the organisation and position types show up as required fields (red square), but adding a position or organisation throws an inline validation error. 

The fields are however not required: just providing a directory title and I can save :-)

![add_directory](https://f.cloud.github.com/assets/394784/2462075/7be9e598-af7d-11e3-98d5-bde61272485e.png)

**Comment by sgeulette** [comment]
It's not due to the token field fill that has been removed. 
It's a datagridfield "bug".
